
version: '3.6'

services:

  jaxy_db:
    image: rac021/jaxy_db_pwd
    hostname: jaxy_db
    environment:
      POSTGRES_USER: jaxy
      POSTGRES_PASSWORD: jaxy
      POSTGRES_DB: aviation
    networks:
      - jaxy_net
      
  jaxy:
    depends_on:
      - jaxy_db
    image: rac021/jaxy:pwd
    hostname: jaxy
    ports:
      - 8181:8181
    volumes:
      - type: bind
        source: /root
        target: /app/jaxy/monitoring_jaxy
    networks:
      - jaxy_net
      
  jaxy_monitoring:
    depends_on:
      - jaxy
    image: rac021/jaxy-monitoring
    hostname: jaxy_monitoring
    environment:
      MONITORING_PATH: /app/mon/provisioning
      TRANSPORT: http
      WAIT: 30
    volumes:
      - type: bind
        source: /root/provisioning
        target: /app/mon/provisioning
    ports:
      - 3000:3000
    networks:
      - jaxy_net

networks:
  jaxy_net: {}
  
