
version: '3.6'

services:

  jaxy_db:
    image: rac021/jaxy_db_pwd
    hostname: jaxy_db
    environment:
      POSTGRES_USER: jaxy
      POSTGRES_PASSWORD: jaxy
      POSTGRES_DB: aviation
    networks:
      - jaxy_net
      
  jaxy:
    depends_on:
      - jaxy_db
    image: rac021/jaxy:pwd
    hostname: jaxy
    ports:
      - 8181:8181
    volumes:
      - /root/monitoring_jaxy:/app/jaxy/monitoring_jaxy
    networks:
      - jaxy_net
      
networks:
  jaxy_net: {}
  
