language: java
sudo: false # faster builds
jdk:
  - oraclejdk8
#before_install:
#  - cd src/jaxy
script:
  - cd src/dependencies/01_jaxy-api 
  - mvn clean package 
  - cd /Jaxy/src/jaxy 
  - mvn clean package
