language: java

sudo: false # faster builds

jdk:
  - oraclejdk8
  
script:
  - cd /home/travis/build/rac021/Jaxy/src/dependencies/01_jaxy-api 
  - mvn clean install
  - cd /home/travis/build/rac021/Jaxy/src/dependencies/02_jaxy-security-provider
  - mvn clean install
  - cd /home/travis/build/rac021/Jaxy/src/dependencies/03_jaxy-service-discovery
  - mvn clean install
  - cd /home/travis/build/rac021/Jaxy/src/dependencies/04_certMe
  - mvn clean install
  - cd /home/travis/build/rac021/Jaxy/src/dependencies/05_jaxyClient
  - mvn clean install
  - cd /home/travis/build/rac021/Jaxy/src/jaxy
  - mvn clean package 
  
jobs:
  include:
    - stage: build docker image
      script:
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - docker build -t jaxy -f jaxy/demo/18_Docker/Dockerfile .
      - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo "snapshot" ; fi`
      - docker images
      - docker tag jaxy $DOCKER_USERNAME/jaxy:$TAG
      - docker push $DOCKER_USERNAME/jaxy:$TAG

