language: java
sudo: false # faster builds
jdk:
  - oraclejdk8
#before_install:
#  - cd src/jaxy
script:
  - cd src/dependencies/01_jaxy-api 
  - mvn clean install
  - cd /home/travis/build/rac021/Jaxy/src/dependencies/02_jaxy-security-provider
  - mvn clean install
