
version: '3.6'

services:

  jaxy_db:
    image: postgres:9.6.11-alpine
    hostname: jaxy_db
    volumes:
      - ./jaxy/demo/18_Docker/db/:/docker-entrypoint-initdb.d/ 
    environment:
      POSTGRES_USER: jaxy
      POSTGRES_PASSWORD: jaxy
      POSTGRES_DB: aviation
    networks:
      - jaxy_net
      
  jaxy:
    depends_on:
      - jaxy_db
    image: rac021/jaxy
    hostname: jaxy
    volumes:
      - ./jaxy/demo/18_Docker/jaxy_test_for_docker/:/app/service rac021/jaxy 
    ports:
      - 8181:8181
    networks:
      - jaxy_net
      
networks:
  jaxy_net: {}
  


