
version: '3.3'

services:

  jaxy_db:
    image: rac021/jaxy_db_pwd
    hostname: jaxy_db
    environment:
      POSTGRES_USER: jaxy
      POSTGRES_PASSWORD: jaxy
      POSTGRES_DB: aviation
    networks:
      - jaxy_net
      
  keycloakme:
    image: rac021/jaxy-keycloakme
    hostname: keycloakme
    ports:
      - 8180:8180
    environment:
      TRANSPORT: http
      MODE: DEMO
    networks:
      - jaxy_net     

  jaxy:
    depends_on:
      - jaxy_db
      - keycloakme
    image: rac021/jaxy:sso-pwd
    hostname: jaxy
    ports:
      - 8181:8181
    volumes:
      - monitoring:/app/jaxy/monitoring_jaxy
      - /docker.log:/app/jaxy/docker/docker.log
    networks:
      - jaxy_net
     
  jaxy_prometheus:
    image: rac021/jaxy-prometheus
    hostname: jaxy_prometheus
    depends_on:
      - jaxy
    environment:
      MONITORING_PATH: /app/mon/provisioning
      JAXY_HOST: jaxy
      JAXY_PORT: 8181
      JAXY_TRANSPORT: http
      SCARPE_INTERVAL: 2s
    volumes:
      - monitoring:/app/mon/
    ports:
      - 9090:9090
    networks:
      - jaxy_net
 
  jaxy_grafana:
    image: rac021/jaxy-grafana
    hostname: jaxy_grafana
    depends_on:
      - jaxy
      - jaxy_prometheus
    environment:
      MONITORING_PATH: /app/mon/provisioning
      PROMETHEUS_URL: http://jaxy_prometheus:9090
    volumes:
      - monitoring:/app/mon/
    ports:
      - 3000:3000
    networks:
      - jaxy_net
 
volumes:
     monitoring: {}
     
networks:
  jaxy_net: {}

